spring.application.name=reservas-cine
spring.datasource.url=jdbc:postgresql://localhost:5432/reservasdb
spring.datasource.username=cine
spring.datasource.password=cine123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379